### ISSUE TITLE
[Roadmap] mgmtsystem_action

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#105]
# Todo
- [x] Add "Actions" menu item under "Management Systems / Reports"
- [x] Add Kanban View
- [x] Include notification to the responsible user when the action is open
- [x] Send a reminder to the responsible user 10 days before the action deadline" ([discussion](https://github.com/OCA/management-system/pull/25#discussion_r30808061))
# Kanban View

In the Kanban view:
- [x] Use color per type:
- Immediate : Red
- Corrective : Orange
- Preventive : Green
- Improvement opportunities : Blue
- [x] Display the responsible user avatar
- [x] Display the deadline
# Reporting

Use the pivot view to compute:
- Number of actions
- Age (now - creation date)
- Number of days to open (opening date - creation date)
- Number of days to close (closing date - opening date)
- Number of exceeding days (closing date - deadline)

and allow grouping by:
- Type
- Creation date
- Opening date
- Closing date
- Deadline
- Responsible
- State
- System

**Comment by max3903** [comment]
#115

**Comment by max3903** [comment]
In the Kanban view:

- [ ] Use color per type
- [ ] Display the responsible user avatar
- [ ] Display the deadline
- [ ] Display the number of messages
