### ISSUE TITLE
[Roadmap] mgmtsystem_nonconformity

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#106]
# Todo
- [x] Replace workflow with Kanban stages
- [x] Add "Nonconformities" menu item under "Management Systems / Reporting"
# Kanban View
- [x] Display the responsible user avatar
# Reporting

Use the pivot view to compute:
- Number of nonconformities
- Age (now - creation date)
- Number of days to analyse (analysis date - creation date)
- Number of days to plan (action plan date - analysis date)
- Number of days to execute (evaluation date - action plan date)
- Number of days to close (closing date - creation date)

and allow grouping by:
- Type
- Date
- Partner
- Responsible
- Manager
- Filled by
- Procedure/Environmental Aspect/Hazard
- Cause
- Origin
- Severity
- Analysis Evaluator
- Plan Evaluator
- Efficiency Evaluator
- Creation date
- Analysis date
- Action plan evaluation date
- Efficiency evaluation date
- Closing date
- State
- System
