### ISSUE TITLE
[Roadmap] mgmtsystem_audit

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#107]
# Todo
- [x] Add "Audits" menu item under "Management Systems / Reporting"
- [x] Hide cancelled improvements opportunities and nonconformities in the report
- [x] Convert verification list report to Qweb
- [x] Convert audit report to Qweb
# Reporting

Use the pivot view to compute:
- Number of audits
- Number of questions in the verification list
- Number of improvements opportunities
- Number of nonconformities
- Age (now - date)
- Number of days to close (closing date - creation date)
- Number of exceeding days (now or closing date - date)

and allow grouping by:
- Audit Manager
- Auditor
- Auditee
- Creation date
- Date
- Closing date
- State
- System

**Comment by dreispt** [comment]
For clearness, add the "roadmap" word to these Issues?

**Comment by naousse** [comment]
@max3903 
Please maxime, where is the difference between date and creation date

**Comment by max3903** [comment]
@naousse On July 22nd, you create an audit and schedule it on August 1st.

Creation date: July 22nd
Date: August 1st
