### ISSUE TITLE
[Roadmap] mgmtsystem

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#110]
Configuration panel available in Management Systems > Configuration > Settings
# Settings

Management Systems
- [ ] Quality (ISO 9001)
- [ ] Environment (ISO 14001)
- [ ] Hygiene & Safety (OHSAS 18001)
- [ ] Information Security (ISO 27001)

Applications
- [ ] Actions (immediate, corrective, preventive) and improvement opportunities
- [ ] Nonconformities
- [ ] Claims
- [ ] Audits
- [ ] Top management reviews
