### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/management-system#159]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] Depends on https://github.com/OCA/knowledge/issues/105

## Quality
- [x] mgmtsystem by @eugen-don in #166
- [x] mgmtsystem_manual by @eugen-don in #167
- [x] document_page_procedure by @eugen-don in #174
- [x] document_page_quality_manual by @eugen-don in #175 
- [x] document_page_work_instruction by @eugen-don in #176
- [x] mgmtsystem_action by @eugen-don in #168 
- [x] mgmtsystem_audit by @eugen-don in #173 
- [x] mgmtsystem_nonconformity by @eugen-don in #169 
- [x] mgmtsystem_survey by @eugen-don in #170 
- [x] mgmtsystem_review by @eugen-don in #171 
- [x] mgmtsystem_quality by @eugen-don in #172 
- [ ] mgmtsystem_kpi
- [ ] mgmtsystem_claim

## Environment
- [ ] document_page_environment_manual
- [ ] document_page_environmental_aspect
- [ ] mgmtsystem_environment

## Health & Safety
- [x] mgmtsystem_hazard by @ngrandjean in #228
- [ ] mgmtsystem_hazard_risk by @ngrandjean in #232 
- [ ] document_page_health_safety_manual
- [ ] mgmtsystem_health_safety

## Information Security
- [ ] mgmtsystem_info_security_manual

## Advanced features
- [ ] mgmtsystem_nonconformity_analytic
- [ ] mgmtsystem_nonconformity_claim
- [ ] mgmtsystem_nonconformity_deptm
- [ ] mgmtsystem_nonconformity_project

## Auditing
- [ ] mgmtsystem_review_audittrail
- [ ] mgmtsystem_hazard_audittrail
- [ ] mgmtsystem_claim_audittrail
- [ ] mgmtsystem_audit_audittrail
- [ ] mgmtsystem_action_audittrail

**Comment by eugen-don** [comment]
@max3903 
Sorry for the late reply, after reading the todo migration tutorial i realized few errors: In the modules mgmtsystem_action, mgmtsystem_nonconformity the mail sending method seems deprecated, i was trying to fix it but cant get it working.

Here are the ported modules so far from repo management-system:
mgmtsystem
mgmtsystem_action
mgmtsystem_audit
mgmtsystem_hazard
mgmtsystem_logistics
mgmtsystem_nonconformity
mgmtsystem_review
mgmtsystem_survey

**Comment by max3903** [comment]
Thanks @eugen-don. Can you make pull requests for each of those modules?

**Comment by eugen-don** [comment]
Hi, im stuck at getting the mail sending methods in mgmtsystem_action to
work correctly.

Ill be done by the end of tomorrow and make a pr.

**Comment by eugen-don** [comment]
@pedrobaeza and @max3903 
HI Guys, as you know im currently porting mgmtsystem_nonconformity to V 10.0
At this moment im updating my PRs in order to meet all of the OCA guidelines and conventions.

While reviewing mgmtsystem_action and mgmtsystem_nonconformity i discovered one of my commented code blocks where i replaced the method for getting the default stage for new actions and nonconformities with the new method odoo uses in its project module. We have in the mgmtsystem_nonconformity the method called _default_stage which is executed on record creation and returns the stage by the stages database ID mgmtsystem_nonconformity.stage_draft...

Odoo on the other hand switched their method to search the project stages for the record, that has its boolean field is_starting set to True and returns this stages id upon record creation. 

This has the advantage that a user can delete the draft stage or even create a new one.

With our current method that returns the default stage by its database ID, the record creation for mgmtsystem_nonconformity fails if a user accidently deletes and reacreates the draft stage, since the database ID of the stage_draft changes.


Should i update the method from:
    def _default_stage(self):
        """Return the default stage."""
        return self.env.ref('mgmtsystem_nonconformity.stage_draft')

to something like ?

    def _default_stage(self):
        return self.env['mgmtsystem.nonconformity.stage'].search(
            [('is_starting', '=', True)],
            limit=1)


Or should the changes be kept as small as possible?

Notice that Odoos aproach to getting the default stage will also fail if the user creates multiple stages with the field is_starting = True

EDIT:

Just found out that replacing the method would require to adjust some more views...
So ill leave the method as it was, since we can still change it later on.

**Comment by pedrobaeza** [comment]
I think the best is to make the PR and comment there instead of polluting this issues that is intended to coordinate migration efforts. I'm only involved in this coordination, not the modules themselves anyway.

**Comment by dreispt** [comment]
@eugen-don Please commit changes on only one module on each PR, otherwise the reviewing process is very unpractical. The build will be red from missing dependencies, but don't worry. As soon as the dependencies are merged, you can rebase it on latest 10.0 and it will (hopefully) go green. 
Don't forget to list the PR dependencies on the PR's description - that will help reviewers on what to look at first.

**Comment by eugen-don** [comment]
@dreispt Thanks, ill update the PRs descriptions today... but first ill update my commits in accordance to the input that @max3903 was kind enough to provide on my fork of this repo.

**Comment by dreispt** [comment]
@eugen-don I'm not sure that your PRs are building on top on the port work already done for 9.0.
Each PR should handle one module, and you should extract the modules change history from 9.0, using the Git black magic explained at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

You should then see in your PRs commits from other people, and that's expected.
Try it on a PR and ping us for a review.

**Comment by eugen-don** [comment]
@dreispt 
thanks for the advice im on it.

**Comment by eugen-don** [comment]
@max3903 @dreispt 

Could we leave my PRs open and only merge them after i write ready to merge in the comments ? Im not completely done with refactoring and am not sure on how to proceed with  mgmtsystem_nonconformity...

**Comment by max3903** [comment]
@eugen-don Just rename the PR with "WIP" as a prefix. Remove it when ready.

**Comment by eugen-don** [comment]
ok thanks

**Comment by ngrandjean** [comment]
Hello everyone,
If no one is working on it I'll do the migration of the following modules:
- mgmtsystem_hazard
- mgmtsystem_hazard_risk
