### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/management-system#200]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

Dependencies on Knowledge:
- [x] https://github.com/OCA/knowledge/issues/147

## Quality

- [x] document_page_procedure by @jalzaga - #214 
- [x] document_page_quality_manual by @jalzaga - #216 
- [x] document_page_work_instruction by @jalzaga - #213 
- [x] mgmtsystem by @jalzaga - #210 
- [x] mgmtsystem_action by @jalzaga - #211 
- [x] mgmtsystem_audit by @jalzaga - #220 
- [x] mgmtsystem_manual by @jalzaga - #215 
- [x] mgmtsystem_nonconformity by @jalzaga - #217 
- [x] mgmtsystem_quality by @jalzaga - #221 
- [x] mgmtsystem_review by @jalzaga - #219 
- [x] mgmtsystem_survey by @jalzaga - #218 

## Environment

- [ ] document_page_environment_manual
- [ ] document_page_environmental_aspect
- [ ] mgmtsystem_environment

## Health & Safety

- [ ] document_page_health_safety_manual
- [ ] mgmtsystem_hazard
- [ ] mgmtsystem_health_safety

## Information Security

- [ ] mgmtsystem_info_security_manual

## Advanced Features

- [ ] mgmtsystem_action_audittrail
- [ ] mgmtsystem_audit_audittrail
- [ ] mgmtsystem_claim
- [ ] mgmtsystem_claim_audittrail
- [ ] mgmtsystem_hazard_audittrail
- [ ] mgmtsystem_kpi
- [ ] mgmtsystem_nonconformity_analytic
- [ ] mgmtsystem_nonconformity_claim
- [ ] mgmtsystem_nonconformity_deptm
- [ ] mgmtsystem_nonconformity_project
- [ ] mgmtsystem_review_audittrail

**Comment by jalzaga** [comment]
Is there a PR for it? we´ll be ready to test as soon as it is available, please inform us if you are going to assign works to other contributors to participate.

**Comment by max3903** [comment]
@jalzaga There is no contributors to work on this yet. If you have resources available (human or financial), please let me know and we can coordinate the effort.

**Comment by jalzaga** [comment]
We can dedicate some time from our resources, both human and financial, take us into account. @max3903

**Comment by jalzaga** [comment]
Migration to version 11.0 @pedrobaeza @max3903  I'm migrating the following modules:
mgmtsystem
mgmtsystem_action
mgmtsystem_audit
mgmtsystem_manual
mgmtsystem_nonconformity
mgmtsystem_quality
mgmtsystem_review
mgmtsystem_survey
document_page_procedure
document_page_quality_manual
document_page_work_instruction

**Comment by pedrobaeza** [comment]
OK, please one module per PR and preserve commit history.

**Comment by SalahAdDin** [comment]
Hi guys, how can i help you with this module? We need this implementation in my work.

**Comment by max3903** [comment]
@SalahAdDin Can you be more specific? Which module do you need?

**Comment by SalahAdDin** [comment]
Knowledge base.

**Comment by akhasis** [comment]
Hi guys!

I'm using this management system in Odoo 8 and about to migrate to Odoo 11. I found this thread and find it very interesting, since I would love to be able to use the Management System after the migration. Is this project still active? Is there any release date for the modules?

Also, the KPI module sounds really useful to me. 

Please note I realize you are working for free and I am in no way trying to hurry you, but to find out if I am going to be able to use the module in Odoo 11.

Keep up the good work!!!

**Comment by pedrobaeza** [comment]
This issue gathers the efforts, so if there is no PR, there are no plans for anybody to migrate them. Most of us have migrated directly to v12 and migrate modules to that version instead.

**Comment by akhasis** [comment]
Thanks for your quick response :D

**Comment by flachica** [comment]
I want to migrate mgmtsystem_hazard module.

**Comment by flachica** [comment]
Sorry, I need mgmtsystem_hazard to v13 but exists a PR yet. Discard this, please.

**Comment by flachica** [comment]
Sorry, I need mgmtsystem_hazard to v13 but exists a PR yet for v12. Discard this, please.
