### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/management-system#442]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] document_page_environment_manual - By @FernandoRomera - #462
- [x] document_page_environmental_aspect - By @FernandoRomera - #463
- [x] document_page_health_safety_manual - By @mymage - #489
- [x] document_page_procedure - By @FernandoRomera - #464
- [x] document_page_quality_manual - By @FernandoRomera - #465
- [x] document_page_work_instruction - By @FernandoRomera - #466
- [x] mgmtsystem - By @FernandoRomera - #458
- [x] mgmtsystem_action - By @FernandoRomera - #467
- [x] mgmtsystem_action_efficacy - By @FernandoRomera - #468
- [x] mgmtsystem_action_template - By @FernandoRomera - #469
- [x] mgmtsystem_audit - By @FernandoRomera - #470
- [x] mgmtsystem_claim - By @mymage - #496
- [x] mgmtsystem_environment - By @mymage - #490
- [x] mgmtsystem_evaluation - By @kluna1998 - #620
- [x] mgmtsystem_evaluation_hr - By @etobella - #655
- [x] mgmtsystem_hazard - By @FernandoRomera - #473
- [x] mgmtsystem_hazard_risk - By @mymage - #491
- [x] mgmtsystem_health_safety - By @mymage - #497
- [x] mgmtsystem_info_security_manual - By @mymage - #492
- [x] mgmtsystem_manual - By @FernandoRomera - #459
- [x] mgmtsystem_nonconformity - By @FernandoRomera - #471
- [x] mgmtsystem_nonconformity_hr - By @FernandoRomera - #476
- [x] mgmtsystem_nonconformity_maintenance - By @ChanGuaZzz - #747
- [x] mgmtsystem_nonconformity_mrp - By @FernandoRomera - #477
- [x] mgmtsystem_nonconformity_product - By @FernandoRomera - #478
- [x] mgmtsystem_nonconformity_quality_control_oca - By @mymage - #498
- [x] mgmtsystem_nonconformity_repair - By @rodrigonevest - #516
- [x] mgmtsystem_nonconformity_type - By @mymage - #493
- [x] mgmtsystem_partner - By @FernandoRomera - #474
- [x] mgmtsystem_quality - By @FernandoRomera - #486
- [x] mgmtsystem_review - By @FernandoRomera - #475
- [x] mgmtsystem_survey - By @FernandoRomera - #472

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by mymage** [comment]
I migrate
- document_page_health_safety_manual #489
- mgmtsystem_environment #490
- mgmtsystem_hazard_risk #491
- mgmtsystem_info_security_manual #492
- mgmtsystem_nonconformity_type #493
- mgmtsystem_claim #496 depends https://github.com/OCA/crm/pull/468
- mgmtsystem_health_safety #497
- mgmtsystem_nonconformity_quality_control_oca #498 depends on https://github.com/OCA/manufacture/pull/923
