### ISSUE TITLE
Migration to version 8.0

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#49]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [x] document_page_environment_manual : #17 
- [x] document_page_environmental_aspect : #52
- [x] document_page_health_safety_manual : #53
- [x] document_page_procedure : #35 
- [x] document_page_quality_manual : #50
- [x] document_page_work_instructions : #26 
- [x] information_security_manual : #18 
- [x] mgmtsystem_action : #22 
- [x] mgmtsystem_audit : #27 
- [x] mgmtsystem_claim : #29 
- [x] mgmtsystem_environment : #54
- [x] mgmtsystem_hazard : #28 
- [x] mgmtsystem_health_safety : #31 
- [ ] mgmtsystem_kpi :
- [x] mgmtsystem_manuals : #23 
- [x] mgmtsystem_nonconformity : #25 
- [x] mgmtsystem_nonconformity_analytic : #32 
- [x] mgmtsystem_nonconformity_claim : #33 
- [ ] mgmtsystem_nonconformity_deptm :
- [x] mgmtsystem_nonconformity_project : #55
- [x] mgmtsystem_quality : #34 
- [x] mgmtsystem_review : #51
- [x] mgmtsystem_survey : #30 
# Being developed on version 7
- [ ] mgmtsystem_probability : 
- [ ] mgmtsystem_security_event : 
- [ ] mgmtsystem_severity : 
# Deprecated modules
- mgmtsystem_action_audittrail
- mgmtsystem_audit_audittrail
- mgmtsystem_claim_audittrail
- mgmtsystem_hazard_audittrail
- mgmtsystem_review_audittrail

**Comment by dreispt** [comment]
Maybe it's easier to follow on this page: https://github.com/OCA/management-system/milestones/8.0

**Comment by dreispt** [comment]
Right now the big bottleneck is on #25

**Comment by bwrsandman** [comment]
`*_audittrail` modules could use auditlog
