### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#522]
- [ ] Add the admin user in the Admin group to access the application
- [ ] Edit the context of the action that open Manuals to see all manuals
- [ ] Add the PDF reports based on QWeb (audit, nonconformity). Look at older version to reproduce the same output.

CC: @SMaciasOSI, @hdelacru

**Comment by Albatros79** [comment]
QMS also contains forms for several occassions but there is no section called forms there , i wonder how can we enter form data and fill & save them when we need it? also Risk Assesment need to be done within the system

**Comment by diggy128** [comment]
@Albatros79 
My 2cents on forms: 
Migrating to ISO 22000, I found myself that most forms dictated by our implementation of the standard are indeed Odoo model records. Since they fulfill the 5Ws + H (who, what, when, where, why and how) and ALL interactions with interested parties (both internal and external) I added a boolean field in ir.models that identifies the model data as a record and used a filtered report of model names as recorded information (which would otherwise be forms and data).

Also mgmtsystem_hazard with a few modification can handle risk assessment nicely (even though not user or report friendly).
