### ISSUE TITLE
Migration to version 9

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#90]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Dependencies
- https://github.com/OCA/knowledge/issues/71
# Modules to migrate
- [ ] mgmtsystem
- [ ] document_page_environment_manual
- [ ] document_page_environmental_aspect
- [ ] document_page_health_safety_manual
- [ ] document_page_procedure
- [ ] document_page_quality_manual
- [ ] document_page_work_instructions
- [ ] information_security_manual
- [ ] mgmtsystem_action
- [ ] mgmtsystem_nonconformity
- [ ] mgmtsystem_nonconformity_analytic
- [ ] mgmtsystem_nonconformity_claim
- [ ] mgmtsystem_claim
- [ ] mgmtsystem_audit
- [ ] mgmtsystem_review
- [ ] mgmtsystem_survey
- [ ] mgmtsystem_quality
- [ ] mgmtsystem_environment
