### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/management-system#92]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Dependencies
- [x] https://github.com/OCA/knowledge/issues/72
# Modules to migrate
- [x] mgmtsystem + improvements (#110) by @naousse in #94 
- [x] mgmtsystem_manuals by @naousse in #95
- Rename module to mgmtsystem_manual
- [x] document_page_work_instructions by @naousse in #98 
- Rename module to document_page_work_instruction
- [x] mgmtsystem_action + improvements (#105) by @naousse in #115 
- [x] mgmtsystem_nonconformity + improvements (#106) by @naousse in #140 
- [x] mgmtsystem_survey by @naousse in #145 
- [x] mgmtsystem_audit + improvements (#107 ) by @naousse in #143, superseeded by #152.
- [x] mgmtsystem_review by @naousse  in #146 
- [ ] mgmtsystem_claim by @Jeroen7V in #141 
- [ ] mgmtsystem_nonconformity_claim by @Jeroen7V
- [x] mgmtsystem_kpi + improvements in #154 by @naousse in #153
- [ ] mgmtsystem_nonconformity_project by @thinkwelltwd in #190 
- [ ] mgmtsystem_nonconformity_analytic
- [ ] mgmtsystem_nonconformity_deptm
## Quality
- [x] document_page_quality_manual by @naousse in #99
- [x] document_page_procedure by @naousse in #100
- [x] mgmtsystem_quality by @naousse in #150 
## Environment
- [x] document_page_environment_manual by @naousse in #96 
- [x] document_page_environmental_aspect by @naousse in #102 
- [ ] mgmtsystem_environment by @Jeroen7V
## Information Security
- [x] information_security_manual by @naousse in #97 
- [x] mgmtsystem_severity by @naousse in #157 
- [x] mgmtsystem_probability by @naousse in #156 
- [ ] mgmtsystem_security_event by @naousse
- [ ] mgmtsystem_information_security by @naousse in #183 
## Health & Safety
- [x] document_page_health_safety_manual by @naousse in #101
- [x] mgmtsystem_hazard by @ngrandjean in #164 
- [ ] mgmtsystem_hazard_risk
- [ ] mgmtsystem_health_safety
# Menu Structure

Management systems
- Actions
- Non-Conformities
- Audits
- Reviews

Documentation
- Work Instructions
- Procedures
- Environmental Aspects
- Hazards
- Manuals

Reports
- KPI
- Actions
- Claims
- Non-Conformities
- Audits

Configuration
- Settings
- Categories
- Same current menu items

**Comment by dreispt** [comment]
Status update: no PR pending reviews, all are expecting action from the authors.

**Comment by max3903** [comment]
@dreispt There is one PR to review: https://github.com/OCA/knowledge/pull/75

**Comment by lukvml** [comment]
Hello,

How can we help to speed up migration to 9.0?
Can we contribute by paying for migration?

**Comment by max3903** [comment]
@lukvml Please contact me privately: maxime DOT chambreuil AT gmail DOT com

**Comment by omerfarooX** [comment]
Hello, Is this module available for Odoo 9?

**Comment by max3903** [comment]
@omer414 Can you be more specific? The modules with a checkmark are migrated, the ones with a link to a PR are in progress, all the others are waiting for some love to be migrated.

**Comment by ngrandjean** [comment]
Hello,

Module mgmtsystem_hazard_risk is not in the list. Is it given up ?

**Comment by max3903** [comment]
Hello @ngrandjean, I just added it to the list.
